--<ScriptOptions statementTerminator=";"/>

CREATE SCHEMA AUTHORIZATION Schema;

CREATE TABLE PAQUETE (
		ITEMCOMPRABLE_ID INTEGER NOT NULL,
		CANTIDAD_JUEGOS INTEGER
	);

CREATE TABLE USUARIO (
		USUARIO_ID INTEGER NOT NULL,
		APODO VARCHAR(50) NOT NULL,
		EMAIL VARCHAR(50) NOT NULL,
		FECHA_NACIMIENTO DATE NOT NULL,
		CONTRASENIA CHAR(5) NOT NULL,
		UBICACION_GEOGRAFICA VARCHAR(50),
		TARJETA BIGINT,
		COMPARTIR_IMAGENES CHAR(1),
		COMPARTIR_VIDEOS CHAR(1),
		COMPARTIR_MENSAJES_PERFIL CHAR(1),
		COMPARTIR_COMPRAS CHAR(1),
		NIVEL INTEGER,
		EXPERIENCIA INTEGER DEFAULT 0
	);

CREATE TABLE NOTIFICACION_COMPRA (
		USUARIO_ID INTEGER NOT NULL,
		COMPRA_ID INTEGER NOT NULL,
		VISTA CHAR(5)
	);

CREATE TABLE MULTIMEDIA_JUEGO (
		MULTIMEDIA_JUEGO_ID INTEGER NOT NULL,
		URL VARCHAR(200) NOT NULL,
		FECHA DATE NOT NULL,
		COMENTARIO VARCHAR(255),
		ITEMCOMPRABLE_ID INTEGER NOT NULL,
		TIPO INTEGER NOT NULL
	);

CREATE TABLE ALBUM (
		ALBUM_ID INTEGER NOT NULL,
		USUARIO_ID INTEGER NOT NULL,
		FECHA_CREACION DATE,
		COMPARTIR CHAR(1)
	);

CREATE TABLE TIPO_CUPON_DESCUENTO (
		TIPO_CUPON_DESCUENTO_ID INTEGER NOT NULL,
		DESCRIPCION VARCHAR(255),
		PORCENTAJE FLOAT NOT NULL,
		DURACION INTEGER NOT NULL
	);

CREATE TABLE JUEGO_DESEADO (
		USUARIO_ID INTEGER NOT NULL,
		RECIBIR_NOTIFICACION CHAR(1) NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE MULTIMEDIA_USUARIO (
		MULTIMEDIA_USUARIO_ID INTEGER NOT NULL,
		ALBUM_ID INTEGER NOT NULL,
		URL VARCHAR(200) NOT NULL,
		FECHA DATE NOT NULL,
		COMENTARIO VARCHAR(255),
		COMPARTIR CHAR(1),
		NOMBRE VARCHAR(50),
		TAMANIO INTEGER,
		TIPO INTEGER
	);

CREATE TABLE MENSAJE_PERFIL (
		MENSAJE_PERFIL_ID INTEGER NOT NULL,
		FECHA DATE NOT NULL,
		COMPARTIR CHAR(1) NOT NULL,
		USUARIO_ID_REMITENTE INTEGER NOT NULL,
		USUARIO_ID_DESTINATARIO INTEGER NOT NULL
	);

CREATE TABLE RED_SOCIAL_USUARIO (
		USUARIO_ID INTEGER NOT NULL,
		RED_SOCIAL_USUARIO_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(30) NOT NULL,
		LINK VARCHAR(255)
	);

CREATE TABLE CUPON_DESCUENTO (
		CUPON_DESCUENTO_ID INTEGER NOT NULL,
		TIPO_CUPON_DESCUENTO_ID INTEGER NOT NULL,
		USUARIO_ID INTEGER,
		FECHA_INICIO DATE NOT NULL
	);

CREATE TABLE DESARROLLADOR (
		DESARROLLADOR_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL
	);

CREATE TABLE BIBLIOTECA (
		USUARIO_ID INTEGER NOT NULL,
		EXPERIENCIA_GANADA INTEGER,
		PORCENTAJE_JUEGO_COMPLETADO FLOAT NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE VIDEO_JUEGO (
		MULTIMEDIA_JUEGO_ID INTEGER NOT NULL,
		DURACION INTEGER
	);

CREATE TABLE JUEGO (
		GENERO_ID INTEGER NOT NULL,
		DESARROLLADOR_ID INTEGER NOT NULL,
		FECHA_LANZAMIENTO DATE,
		DISPONIBLE CHAR(1) DEFAULT '0' NOT NULL,
		MODO SMALLINT NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE DESCUENTO (
		DESCUENTO_ID INTEGER NOT NULL,
		PORCENTAJE FLOAT NOT NULL,
		DESCRIPCION VARCHAR(255),
		FECHA_INICIO DATE NOT NULL,
		FECHA_FIN DATE NOT NULL
	);

CREATE TABLE SIMILITUD (
		USUARIO_ID_1 INTEGER NOT NULL,
		USUARIO_ID_2 INTEGER NOT NULL,
		FECHA DATE NOT NULL
	);

CREATE TABLE VIDEO_USUARIO (
		DURACION INTEGER,
		MULTIMEDIA_USUARIO_ID INTEGER NOT NULL
	);

CREATE TABLE PETICION_AMISTAD (
		USUARIO_ID_REMITENTE INTEGER NOT NULL,
		USUARIO_ID_DESTINATARIO INTEGER NOT NULL,
		FECHA DATE NOT NULL,
		RESPUESTA CHAR(1),
		FECHA_RESPUESTA DATE
	);

CREATE TABLE LOGRO (
		LOGRO_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL,
		DESCRIPCION VARCHAR(255) NOT NULL,
		EXPERIENCIA INTEGER NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE ITEM_COMPRABLE (
		ITEMCOMPRABLE_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(50),
		PRECIO FLOAT,
		DESCRIPCION VARCHAR(250),
		TIPO_ITEM INTEGER
	);

CREATE TABLE RECOMENDACION (
		RECOMENDACION_ID INTEGER NOT NULL,
		USUARIO_ID_REMITENTE INTEGER NOT NULL,
		USUARIO_ID_DESTINATARIO INTEGER,
		EMAIL_DESTINATARIO VARCHAR(50),
		ITEMCOMPRABLE_ID INTEGER
	);

CREATE TABLE LOG_LOGRO_USUARIO (
		USUARIO_ID INTEGER NOT NULL,
		LOGRO_ID INTEGER NOT NULL,
		FECHA DATE NOT NULL
	);

CREATE TABLE AMISTAD (
		USUARIO_ID_1 INTEGER NOT NULL,
		USUARIO_ID_2 INTEGER NOT NULL,
		ESTADO CHAR(1) NOT NULL
	);

CREATE TABLE COMENTARIO_JUEGO (
		USUARIO_ID INTEGER NOT NULL,
		COMENTARIO VARCHAR(255) NOT NULL,
		PUNTAJE SMALLINT NOT NULL,
		COMETARIO_ID CHAR(5) NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE IMAGEN_USUAIRO (
		RESOLUCION VARCHAR(20),
		MULTIMEDIA_USUARIO_ID INTEGER NOT NULL
	);

CREATE TABLE OBSEQUIO (
		OBSEQUIO_ID INTEGER NOT NULL,
		ITEM_COMPRA_ID INTEGER,
		USUARIO_ID_DESTINATARIO INTEGER,
		FECHA DATE
	);

CREATE TABLE KEY_ITEM_COMPRABLE (
		KEY_ID INTEGER NOT NULL,
		KEY_ITEM CHAR(50),
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE IMAGEN_JUEGO (
		MULTIMEDIA_JUEGO_ID INTEGER NOT NULL,
		RESOLUCION VARCHAR(20)
	);

CREATE TABLE CONTENIDO_PAQUETE (
		ITEMCOMPRABLE_JUEGO_ID INTEGER NOT NULL,
		ITEMCOMPRABLE_PAQUETE_ID1 INTEGER NOT NULL
	);

CREATE TABLE DESCUENTO_ITEM_COMPRABLE (
		DESCUENTO_ID INTEGER NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE JUEGO_PREFERIDO (
		USUARIO_ID INTEGER NOT NULL,
		ORDEN INTEGER NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE COMPRA (
		COMPRA_ID INTEGER NOT NULL,
		COMPRA_FECHA DATE NOT NULL,
		USUARIO_ID INTEGER NOT NULL
	);

CREATE TABLE GENERO (
		GENERO_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL
	);

CREATE TABLE ITEM_COMPRA (
		ITEM_COMPRA_ID INTEGER NOT NULL,
		COMPRA_ID INTEGER NOT NULL,
		VALOR FLOAT NOT NULL,
		DESCUENTO_ID INTEGER,
		CUPON_DESCUENTO_ID INTEGER,
		KEY_ID INTEGER NOT NULL
	);

ALTER TABLE GENERO ADD CONSTRAINT PRIMARY KEY
	(GENERO_ID)
	CONSTRAINT GENERO_PK;

ALTER TABLE PAQUETE ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_ID)
	CONSTRAINT PAQUETE_PK;

ALTER TABLE PETICION_AMISTAD ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID_REMITENTE,
	 USUARIO_ID_DESTINATARIO)
	CONSTRAINT PETICION_AMISTAD_PK;

ALTER TABLE LOGRO ADD CONSTRAINT PRIMARY KEY
	(LOGRO_ID)
	CONSTRAINT LOGRO_PK;

ALTER TABLE ALBUM ADD CONSTRAINT PRIMARY KEY
	(ALBUM_ID)
	CONSTRAINT ALBUM_PK;

ALTER TABLE MULTIMEDIA_JUEGO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT MULTIMEDIA_JUEGO_PK;

ALTER TABLE ITEM_COMPRABLE ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_ID)
	CONSTRAINT ITEM_COMPRABLE_PK;

ALTER TABLE LOG_LOGRO_USUARIO ADD CONSTRAINT PRIMARY KEY
	(LOGRO_ID,
	 USUARIO_ID)
	CONSTRAINT LOG_LOGRO_USUARIO_PK;

ALTER TABLE AMISTAD ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID_1,
	 USUARIO_ID_2)
	CONSTRAINT AMISTAD_PK;

ALTER TABLE COMENTARIO_JUEGO ADD CONSTRAINT PRIMARY KEY
	(COMETARIO_ID,
	 USUARIO_ID)
	CONSTRAINT COMENTARIO_JUEGO_PK;

ALTER TABLE JUEGO ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_ID)
	CONSTRAINT JUEGO_PK;

ALTER TABLE RECOMENDACION ADD CONSTRAINT PRIMARY KEY
	(RECOMENDACION_ID)
	CONSTRAINT RECOMENDACION_PK;

ALTER TABLE KEY_ITEM_COMPRABLE ADD CONSTRAINT PRIMARY KEY
	(KEY_ID)
	CONSTRAINT KEY_ITEM_COMPRABLE_PK;

ALTER TABLE CUPON_DESCUENTO ADD CONSTRAINT PRIMARY KEY
	(CUPON_DESCUENTO_ID)
	CONSTRAINT CUPON_DESCUENTO_PK;

ALTER TABLE JUEGO_PREFERIDO ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID)
	CONSTRAINT JUEGO_PREFERIDO_PK;

ALTER TABLE COMPRA ADD CONSTRAINT PRIMARY KEY
	(COMPRA_ID)
	CONSTRAINT COMPRA_PK;

ALTER TABLE TIPO_CUPON_DESCUENTO ADD CONSTRAINT PRIMARY KEY
	(TIPO_CUPON_DESCUENTO_ID)
	CONSTRAINT TIPO_CUPON_DESCUENTO_PK;

ALTER TABLE DESARROLLADOR ADD CONSTRAINT PRIMARY KEY
	(DESARROLLADOR_ID)
	CONSTRAINT DESARROLLADOR_PK;

ALTER TABLE RED_SOCIAL_USUARIO ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID,
	 RED_SOCIAL_USUARIO_ID)
	CONSTRAINT RED_SOCIAL_USUARIO_PK;

ALTER TABLE VIDEO_JUEGO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT VIDEO_JUEGO_PK;

ALTER TABLE BIBLIOTECA ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_ID,
	 USUARIO_ID)
	CONSTRAINT BIBLIOTECA_PK;

ALTER TABLE USUARIO ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID)
	CONSTRAINT USUARIO_PK;

ALTER TABLE VIDEO_USUARIO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT VIDEO_USUARIO_PK;

ALTER TABLE NOTIFICACION_COMPRA ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID,
	 COMPRA_ID)
	CONSTRAINT NOTIFICACION_COMPRA_PK;

ALTER TABLE OBSEQUIO ADD CONSTRAINT PRIMARY KEY
	(OBSEQUIO_ID)
	CONSTRAINT OBSEQUIO_PK;

ALTER TABLE MULTIMEDIA_USUARIO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT MULTIMEDIA_USUARIO_PK;

ALTER TABLE ITEM_COMPRA ADD CONSTRAINT PRIMARY KEY
	(ITEM_COMPRA_ID)
	CONSTRAINT ITEM_COMPRA_PK;

ALTER TABLE JUEGO_DESEADO ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID)
	CONSTRAINT JUEGO_DESEADO_PK;

ALTER TABLE IMAGEN_USUAIRO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT IMAGEN_USUAIRO_PK;

ALTER TABLE SIMILITUD ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID_1,
	 USUARIO_ID_2)
	CONSTRAINT SIMILITUD_PK;

ALTER TABLE DESCUENTO_ITEM_COMPRABLE ADD CONSTRAINT PRIMARY KEY
	(DESCUENTO_ID,
	 ITEMCOMPRABLE_ID)
	CONSTRAINT DESCUENTO_ITEM_COMPRABLE_PK;

ALTER TABLE MENSAJE_PERFIL ADD CONSTRAINT PRIMARY KEY
	(MENSAJE_PERFIL_ID)
	CONSTRAINT MENSAJE_PERFIL_PK;

ALTER TABLE IMAGEN_JUEGO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT IMAGEN_JUEGO_PK;

ALTER TABLE DESCUENTO ADD CONSTRAINT PRIMARY KEY
	(DESCUENTO_ID)
	CONSTRAINT DESCUENTO_PK;

ALTER TABLE CONTENIDO_PAQUETE ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_JUEGO_ID,
	 ITEMCOMPRABLE_PAQUETE_ID1)
	CONSTRAINT CONTENIDO_PAQUETE_PK;

ALTER TABLE JUEGO_DESEADO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT JUEGO_DESEADO_JUEGO_FK;

ALTER TABLE KEY_ITEM_COMPRABLE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT KEY_ITEM_COMPRABLE_ITEM_COMPRABLE_FK;

ALTER TABLE OBSEQUIO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_DESTINATARIO)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT OBSEQUIO_USUARIO_FK;

ALTER TABLE LOG_LOGRO_USUARIO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT LOG_LOGRO_USUARIO_USUARIO_FK;

ALTER TABLE VIDEO_JUEGO ADD CONSTRAINT FOREIGN KEY
	(MULTIMEDIA_JUEGO_ID)
	REFERENCES MULTIMEDIA_JUEGO
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT VIDEO_JUEGO_MULTIMEDIA_JUEGO_FK;

ALTER TABLE LOG_LOGRO_USUARIO ADD CONSTRAINT FOREIGN KEY
	(LOGRO_ID)
	REFERENCES LOGRO
	(LOGRO_ID)
	CONSTRAINT LOG_LOGRO_USUARIO_LOGRO_FK;

ALTER TABLE RED_SOCIAL_USUARIO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT RED_SOCIAL_USUARIO_USUARIO_FK;

ALTER TABLE MENSAJE_PERFIL ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_DESTINATARIO)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT MENSAJE_PERFIL_USUARIO_FK1;

ALTER TABLE LOGRO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT LOGRO_JUEGO_FK;

ALTER TABLE ALBUM ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT ALBUM_USUARIO_FK;

ALTER TABLE ITEM_COMPRA ADD CONSTRAINT FOREIGN KEY
	(DESCUENTO_ID)
	REFERENCES DESCUENTO
	(DESCUENTO_ID)
	CONSTRAINT ITEM_COMPRA_DESCUENTO_FK;

ALTER TABLE JUEGO_DESEADO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT JUEGO_DESEADO_USUARIO_FK;

ALTER TABLE ITEM_COMPRA ADD CONSTRAINT FOREIGN KEY
	(KEY_ID)
	REFERENCES KEY_ITEM_COMPRABLE
	(KEY_ID)
	CONSTRAINT ITEM_COMPRA_KEY_ITEM_COMPRABLE_FK;

ALTER TABLE SIMILITUD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_1)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT SIMILITUD_USUARIO_FK;

ALTER TABLE DESCUENTO_ITEM_COMPRABLE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT DESCUENTO_ITEM_COMPRABLE_ITEM_COMPRABLE_FK;

ALTER TABLE RECOMENDACION ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT RECOMENDACION_ITEM_COMPRABLE_FK;

ALTER TABLE JUEGO ADD CONSTRAINT FOREIGN KEY
	(GENERO_ID)
	REFERENCES GENERO
	(GENERO_ID)
	CONSTRAINT JUEGO_GENERO_FK;

ALTER TABLE AMISTAD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_1)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT AMISTAD_USUARIO_FK;

ALTER TABLE BIBLIOTECA ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT BIBLIOTECA_JUEGO_FK;

ALTER TABLE MENSAJE_PERFIL ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_REMITENTE)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT MENSAJE_PERFIL_USUARIO_FK;

ALTER TABLE NOTIFICACION_COMPRA ADD CONSTRAINT FOREIGN KEY
	(COMPRA_ID)
	REFERENCES COMPRA
	(COMPRA_ID)
	CONSTRAINT NOTIFICACION_COMPRA_COMPRA_FK;

ALTER TABLE PAQUETE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT PAQUETE_ITEM_COMPRABLE_FK;

ALTER TABLE NOTIFICACION_COMPRA ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT NOTIFICACION_COMPRA_USUARIO_FK;

ALTER TABLE COMPRA ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT COMPRA_USUARIO_FK;

ALTER TABLE MULTIMEDIA_USUARIO ADD CONSTRAINT FOREIGN KEY
	(ALBUM_ID)
	REFERENCES ALBUM
	(ALBUM_ID)
	CONSTRAINT MULTIMEDIA_USUARIO_ALBUM_FK;

ALTER TABLE RECOMENDACION ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_DESTINATARIO)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT RECOMENDACION_USUARIO_FK1;

ALTER TABLE ITEM_COMPRA ADD CONSTRAINT FOREIGN KEY
	(COMPRA_ID)
	REFERENCES COMPRA
	(COMPRA_ID)
	CONSTRAINT ITEM_COMPRA_COMPRA_FK;

ALTER TABLE OBSEQUIO ADD CONSTRAINT FOREIGN KEY
	(ITEM_COMPRA_ID)
	REFERENCES ITEM_COMPRA
	(ITEM_COMPRA_ID)
	CONSTRAINT OBSEQUIO_ITEM_COMPRA_FK;

ALTER TABLE PETICION_AMISTAD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_DESTINATARIO)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT PETICION_AMISTAD_USUARIO_FK1;

ALTER TABLE JUEGO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT JUEGO_ITEM_COMPRABLE_FK;

ALTER TABLE IMAGEN_JUEGO ADD CONSTRAINT FOREIGN KEY
	(MULTIMEDIA_JUEGO_ID)
	REFERENCES MULTIMEDIA_JUEGO
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT IMAGEN_JUEGO_MULTIMEDIA_JUEGO_FK;

ALTER TABLE CONTENIDO_PAQUETE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_PAQUETE_ID1)
	REFERENCES PAQUETE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT CONTENIDO_PAQUETE_PAQUETE_FK;

ALTER TABLE PETICION_AMISTAD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_REMITENTE)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT PETICION_AMISTAD_USUARIO_FK;

ALTER TABLE CONTENIDO_PAQUETE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_JUEGO_ID)
	REFERENCES JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT CONTENIDO_PAQUETE_JUEGO_FK;

ALTER TABLE COMENTARIO_JUEGO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT COMENTARIO_JUEGO_USUARIO_FK;

ALTER TABLE JUEGO_PREFERIDO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT JUEGO_PREFERIDO_JUEGO_FK;

ALTER TABLE CUPON_DESCUENTO ADD CONSTRAINT FOREIGN KEY
	(TIPO_CUPON_DESCUENTO_ID)
	REFERENCES TIPO_CUPON_DESCUENTO
	(TIPO_CUPON_DESCUENTO_ID)
	CONSTRAINT CUPON_DESCUENTO_TIPO_CUPON_DESCUENTO_FK;

ALTER TABLE MULTIMEDIA_JUEGO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT MULTIMEDIA_JUEGO_JUEGO_FK;

ALTER TABLE RECOMENDACION ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_REMITENTE)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT RECOMENDACION_USUARIO_FK;

ALTER TABLE JUEGO ADD CONSTRAINT FOREIGN KEY
	(DESARROLLADOR_ID)
	REFERENCES DESARROLLADOR
	(DESARROLLADOR_ID)
	CONSTRAINT JUEGO_DESARROLLADOR_FK;

ALTER TABLE VIDEO_USUARIO ADD CONSTRAINT FOREIGN KEY
	(MULTIMEDIA_USUARIO_ID)
	REFERENCES MULTIMEDIA_USUARIO
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT VIDEO_USUARIO_MULTIMEDIA_USUARIO_FK;

ALTER TABLE SIMILITUD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_2)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT SIMILITUD_USUARIO_FK1;

ALTER TABLE BIBLIOTECA ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT BIBLIOTECA_USUARIO_FK;

ALTER TABLE COMENTARIO_JUEGO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT COMENTARIO_JUEGO_JUEGO_FK;

ALTER TABLE AMISTAD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_2)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT AMISTAD_USUARIO_FK1;

ALTER TABLE ITEM_COMPRA ADD CONSTRAINT FOREIGN KEY
	(CUPON_DESCUENTO_ID)
	REFERENCES CUPON_DESCUENTO
	(CUPON_DESCUENTO_ID)
	CONSTRAINT ITEM_COMPRA_CUPON_DESCUENTO_FK;

ALTER TABLE JUEGO_PREFERIDO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT JUEGO_PREFERIDO_USUARIO_FK;

ALTER TABLE CUPON_DESCUENTO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES USUARIO
	(USUARIO_ID)
	CONSTRAINT CUPON_DESCUENTO_USUARIO_FK;

ALTER TABLE DESCUENTO_ITEM_COMPRABLE ADD CONSTRAINT FOREIGN KEY
	(DESCUENTO_ID)
	REFERENCES DESCUENTO
	(DESCUENTO_ID)
	CONSTRAINT DESCUENTO_ITEM_COMPRABLE_DESCUENTO_FK;

ALTER TABLE IMAGEN_USUAIRO ADD CONSTRAINT FOREIGN KEY
	(MULTIMEDIA_USUARIO_ID)
	REFERENCES MULTIMEDIA_USUARIO
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT IMAGEN_USUAIRO_MULTIMEDIA_USUARIO_FK;

