--<ScriptOptions statementTerminator=";"/>

CREATE SCHEMA AUTHORIZATION Schema;

CREATE TABLE Schema.TIPO_CUPON_DESCUENTO (
		TIPO_CUPON_DESCUENTO_ID INTEGER NOT NULL,
		DESCRIPCION VARCHAR(255),
		PORCENTAJE FLOAT NOT NULL,
		DURACION INTEGER NOT NULL
	);

CREATE TABLE Schema.BIBLIOTECA (
		USUARIO_ID INTEGER NOT NULL,
		EXPERIENCIA_GANADA INTEGER,
		PORCENTAJE_JUEGO_COMPLETADO FLOAT NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.KEY_ITEM_COMPRABLE (
		KEY_ID INTEGER NOT NULL,
		KEY_ITEM CHAR(50),
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.LOG_LOGRO_USUARIO (
		USUARIO_ID INTEGER NOT NULL,
		LOGRO_ID INTEGER NOT NULL,
		FECHA DATE NOT NULL
	);

CREATE TABLE Schema.SIMILITUD (
		USUARIO_ID_1 INTEGER NOT NULL,
		USUARIO_ID_2 INTEGER NOT NULL,
		FECHA DATE NOT NULL
	);

CREATE TABLE Schema.NOTIFICACION_COMPRA (
		USUARIO_ID INTEGER NOT NULL,
		COMPRA_ID INTEGER NOT NULL,
		VISTA CHAR(5)
	);

CREATE TABLE Schema.CONTENIDO_PAQUETE (
		ITEMCOMPRABLE_JUEGO_ID INTEGER NOT NULL,
		ITEMCOMPRABLE_PAQUETE_ID1 INTEGER NOT NULL
	);

CREATE TABLE Schema.ALBUM (
		ALBUM_ID INTEGER NOT NULL,
		USUARIO_ID INTEGER NOT NULL,
		FECHA_CREACION DATE,
		COMPARTIR CHAR(1)
	);

CREATE TABLE Schema.JUEGO_DESEADO (
		USUARIO_ID INTEGER NOT NULL,
		RECIBIR_NOTIFICACION CHAR(1) NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.DESARROLLADOR (
		DESARROLLADOR_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL
	);

CREATE TABLE Schema.GENERO (
		GENERO_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL
	);

CREATE TABLE Schema.VIDEO_JUEGO (
		MULTIMEDIA_JUEGO_ID INTEGER NOT NULL,
		DURACION INTEGER
	);

CREATE TABLE Schema.USUARIO (
		USUARIO_ID INTEGER NOT NULL,
		APODO VARCHAR(50) NOT NULL,
		EMAIL VARCHAR(50) NOT NULL,
		FECHA_NACIMIENTO DATE NOT NULL,
		CONTRASENIA CHAR(5) NOT NULL,
		UBICACION_GEOGRAFICA VARCHAR(50),
		TARJETA BIGINT,
		COMPARTIR_IMAGENES CHAR(1),
		COMPARTIR_VIDEOS CHAR(1),
		COMPARTIR_MENSAJES_PERFIL CHAR(1),
		COMPARTIR_COMPRAS CHAR(1),
		NIVEL INTEGER,
		EXPERIENCIA INTEGER DEFAULT 0
	);

CREATE TABLE Schema.CUPON_DESCUENTO (
		CUPON_DESCUENTO_ID INTEGER NOT NULL,
		TIPO_CUPON_DESCUENTO_ID INTEGER NOT NULL,
		USUARIO_ID INTEGER,
		FECHA_INICIO DATE NOT NULL
	);

CREATE TABLE Schema.MULTIMEDIA_JUEGO (
		MULTIMEDIA_JUEGO_ID INTEGER NOT NULL,
		URL VARCHAR(200) NOT NULL,
		FECHA DATE NOT NULL,
		COMENTARIO VARCHAR(255),
		ITEMCOMPRABLE_ID INTEGER NOT NULL,
		TIPO INTEGER NOT NULL
	);

CREATE TABLE Schema.ITEM_COMPRABLE (
		ITEMCOMPRABLE_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(50),
		PRECIO FLOAT,
		DESCRIPCION VARCHAR(250),
		TIPO_ITEM INTEGER
	);

CREATE TABLE Schema.AMISTAD (
		USUARIO_ID_1 INTEGER NOT NULL,
		USUARIO_ID_2 INTEGER NOT NULL,
		ESTADO CHAR(1) NOT NULL
	);

CREATE TABLE Schema.COMENTARIO_JUEGO (
		USUARIO_ID INTEGER NOT NULL,
		COMENTARIO VARCHAR(255) NOT NULL,
		PUNTAJE SMALLINT NOT NULL,
		COMETARIO_ID CHAR(5) NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.ITEM_COMPRA (
		ITEM_COMPRA_ID INTEGER NOT NULL,
		COMPRA_ID INTEGER NOT NULL,
		VALOR FLOAT NOT NULL,
		DESCUENTO_ID INTEGER,
		CUPON_DESCUENTO_ID INTEGER,
		KEY_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.IMAGEN_JUEGO (
		MULTIMEDIA_JUEGO_ID INTEGER NOT NULL,
		RESOLUCION VARCHAR(20)
	);

CREATE TABLE Schema.PAQUETE (
		ITEMCOMPRABLE_ID INTEGER NOT NULL,
		CANTIDAD_JUEGOS INTEGER
	);

CREATE TABLE Schema.DESCUENTO (
		DESCUENTO_ID INTEGER NOT NULL,
		PORCENTAJE FLOAT NOT NULL,
		DESCRIPCION VARCHAR(255),
		FECHA_INICIO DATE NOT NULL,
		FECHA_FIN DATE NOT NULL
	);

CREATE TABLE Schema.PETICION_AMISTAD (
		USUARIO_ID_REMITENTE INTEGER NOT NULL,
		USUARIO_ID_DESTINATARIO INTEGER NOT NULL,
		FECHA DATE NOT NULL,
		RESPUESTA CHAR(1),
		FECHA_RESPUESTA DATE
	);

CREATE TABLE Schema.RED_SOCIAL_USUARIO (
		USUARIO_ID INTEGER NOT NULL,
		RED_SOCIAL_USUARIO_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(30) NOT NULL,
		LINK VARCHAR(255)
	);

CREATE TABLE Schema.COMPRA (
		COMPRA_ID INTEGER NOT NULL,
		COMPRA_FECHA DATE NOT NULL,
		USUARIO_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.VIDEO_USUARIO (
		DURACION INTEGER,
		MULTIMEDIA_USUARIO_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.JUEGO (
		GENERO_ID INTEGER NOT NULL,
		DESARROLLADOR_ID INTEGER NOT NULL,
		FECHA_LANZAMIENTO DATE,
		DISPONIBLE CHAR(1) DEFAULT '0' NOT NULL,
		MODO SMALLINT NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.RECOMENDACION (
		RECOMENDACION_ID INTEGER NOT NULL,
		USUARIO_ID_REMITENTE INTEGER NOT NULL,
		USUARIO_ID_DESTINATARIO INTEGER,
		EMAIL_DESTINATARIO VARCHAR(50),
		ITEMCOMPRABLE_ID INTEGER
	);

CREATE TABLE Schema.LOGRO (
		LOGRO_ID INTEGER NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL,
		DESCRIPCION VARCHAR(255) NOT NULL,
		EXPERIENCIA INTEGER NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.MENSAJE_PERFIL (
		MENSAJE_PERFIL_ID INTEGER NOT NULL,
		FECHA DATE NOT NULL,
		COMPARTIR CHAR(1) NOT NULL,
		USUARIO_ID_REMITENTE INTEGER NOT NULL,
		USUARIO_ID_DESTINATARIO INTEGER NOT NULL
	);

CREATE TABLE Schema.DESCUENTO_ITEM_COMPRABLE (
		DESCUENTO_ID INTEGER NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.MULTIMEDIA_USUARIO (
		MULTIMEDIA_USUARIO_ID INTEGER NOT NULL,
		ALBUM_ID INTEGER NOT NULL,
		URL VARCHAR(200) NOT NULL,
		FECHA DATE NOT NULL,
		COMENTARIO VARCHAR(255),
		COMPARTIR CHAR(1),
		NOMBRE VARCHAR(50),
		TAMANIO INTEGER,
		TIPO INTEGER
	);

CREATE TABLE Schema.JUEGO_PREFERIDO (
		USUARIO_ID INTEGER NOT NULL,
		ORDEN INTEGER NOT NULL,
		ITEMCOMPRABLE_ID INTEGER NOT NULL
	);

CREATE TABLE Schema.OBSEQUIO (
		OBSEQUIO_ID INTEGER NOT NULL,
		ITEM_COMPRA_ID INTEGER,
		USUARIO_ID_DESTINATARIO INTEGER,
		FECHA DATE
	);

CREATE TABLE Schema.IMAGEN_USUAIRO (
		RESOLUCION VARCHAR(20),
		MULTIMEDIA_USUARIO_ID INTEGER NOT NULL
	);

ALTER TABLE Schema.JUEGO_PREFERIDO ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID)
	CONSTRAINT JUEGO_PREFERIDO_PK;

ALTER TABLE Schema.VIDEO_JUEGO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT VIDEO_JUEGO_PK;

ALTER TABLE Schema.DESARROLLADOR ADD CONSTRAINT PRIMARY KEY
	(DESARROLLADOR_ID)
	CONSTRAINT DESARROLLADOR_PK;

ALTER TABLE Schema.GENERO ADD CONSTRAINT PRIMARY KEY
	(GENERO_ID)
	CONSTRAINT GENERO_PK;

ALTER TABLE Schema.LOG_LOGRO_USUARIO ADD CONSTRAINT PRIMARY KEY
	(LOGRO_ID,
	 USUARIO_ID)
	CONSTRAINT LOG_LOGRO_USUARIO_PK;

ALTER TABLE Schema.SIMILITUD ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID_1,
	 USUARIO_ID_2)
	CONSTRAINT SIMILITUD_PK;

ALTER TABLE Schema.KEY_ITEM_COMPRABLE ADD CONSTRAINT PRIMARY KEY
	(KEY_ID)
	CONSTRAINT KEY_ITEM_COMPRABLE_PK;

ALTER TABLE Schema.IMAGEN_JUEGO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT IMAGEN_JUEGO_PK;

ALTER TABLE Schema.NOTIFICACION_COMPRA ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID,
	 COMPRA_ID)
	CONSTRAINT NOTIFICACION_COMPRA_PK;

ALTER TABLE Schema.RED_SOCIAL_USUARIO ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID,
	 RED_SOCIAL_USUARIO_ID)
	CONSTRAINT RED_SOCIAL_USUARIO_PK;

ALTER TABLE Schema.JUEGO ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_ID)
	CONSTRAINT JUEGO_PK;

ALTER TABLE Schema.OBSEQUIO ADD CONSTRAINT PRIMARY KEY
	(OBSEQUIO_ID)
	CONSTRAINT OBSEQUIO_PK;

ALTER TABLE Schema.PAQUETE ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_ID)
	CONSTRAINT PAQUETE_PK;

ALTER TABLE Schema.JUEGO_DESEADO ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID)
	CONSTRAINT JUEGO_DESEADO_PK;

ALTER TABLE Schema.COMENTARIO_JUEGO ADD CONSTRAINT PRIMARY KEY
	(COMETARIO_ID,
	 USUARIO_ID)
	CONSTRAINT COMENTARIO_JUEGO_PK;

ALTER TABLE Schema.VIDEO_USUARIO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT VIDEO_USUARIO_PK;

ALTER TABLE Schema.USUARIO ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID)
	CONSTRAINT USUARIO_PK;

ALTER TABLE Schema.MULTIMEDIA_USUARIO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT MULTIMEDIA_USUARIO_PK;

ALTER TABLE Schema.ITEM_COMPRABLE ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_ID)
	CONSTRAINT ITEM_COMPRABLE_PK;

ALTER TABLE Schema.AMISTAD ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID_1,
	 USUARIO_ID_2)
	CONSTRAINT AMISTAD_PK;

ALTER TABLE Schema.DESCUENTO_ITEM_COMPRABLE ADD CONSTRAINT PRIMARY KEY
	(DESCUENTO_ID,
	 ITEMCOMPRABLE_ID)
	CONSTRAINT DESCUENTO_ITEM_COMPRABLE_PK;

ALTER TABLE Schema.TIPO_CUPON_DESCUENTO ADD CONSTRAINT PRIMARY KEY
	(TIPO_CUPON_DESCUENTO_ID)
	CONSTRAINT TIPO_CUPON_DESCUENTO_PK;

ALTER TABLE Schema.PETICION_AMISTAD ADD CONSTRAINT PRIMARY KEY
	(USUARIO_ID_REMITENTE,
	 USUARIO_ID_DESTINATARIO)
	CONSTRAINT PETICION_AMISTAD_PK;

ALTER TABLE Schema.IMAGEN_USUAIRO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT IMAGEN_USUAIRO_PK;

ALTER TABLE Schema.RECOMENDACION ADD CONSTRAINT PRIMARY KEY
	(RECOMENDACION_ID)
	CONSTRAINT RECOMENDACION_PK;

ALTER TABLE Schema.DESCUENTO ADD CONSTRAINT PRIMARY KEY
	(DESCUENTO_ID)
	CONSTRAINT DESCUENTO_PK;

ALTER TABLE Schema.MENSAJE_PERFIL ADD CONSTRAINT PRIMARY KEY
	(MENSAJE_PERFIL_ID)
	CONSTRAINT MENSAJE_PERFIL_PK;

ALTER TABLE Schema.ALBUM ADD CONSTRAINT PRIMARY KEY
	(ALBUM_ID)
	CONSTRAINT ALBUM_PK;

ALTER TABLE Schema.LOGRO ADD CONSTRAINT PRIMARY KEY
	(LOGRO_ID)
	CONSTRAINT LOGRO_PK;

ALTER TABLE Schema.MULTIMEDIA_JUEGO ADD CONSTRAINT PRIMARY KEY
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT MULTIMEDIA_JUEGO_PK;

ALTER TABLE Schema.ITEM_COMPRA ADD CONSTRAINT PRIMARY KEY
	(ITEM_COMPRA_ID)
	CONSTRAINT ITEM_COMPRA_PK;

ALTER TABLE Schema.BIBLIOTECA ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_ID,
	 USUARIO_ID)
	CONSTRAINT BIBLIOTECA_PK;

ALTER TABLE Schema.CONTENIDO_PAQUETE ADD CONSTRAINT PRIMARY KEY
	(ITEMCOMPRABLE_JUEGO_ID,
	 ITEMCOMPRABLE_PAQUETE_ID1)
	CONSTRAINT CONTENIDO_PAQUETE_PK;

ALTER TABLE Schema.COMPRA ADD CONSTRAINT PRIMARY KEY
	(COMPRA_ID)
	CONSTRAINT COMPRA_PK;

ALTER TABLE Schema.CUPON_DESCUENTO ADD CONSTRAINT PRIMARY KEY
	(CUPON_DESCUENTO_ID)
	CONSTRAINT CUPON_DESCUENTO_PK;

ALTER TABLE Schema.PETICION_AMISTAD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_REMITENTE)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT PETICION_AMISTAD_USUARIO_FK;

ALTER TABLE Schema.IMAGEN_USUAIRO ADD CONSTRAINT FOREIGN KEY
	(MULTIMEDIA_USUARIO_ID)
	REFERENCES Schema.MULTIMEDIA_USUARIO
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT IMAGEN_USUAIRO_MULTIMEDIA_USUARIO_FK;

ALTER TABLE Schema.JUEGO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT JUEGO_ITEM_COMPRABLE_FK;

ALTER TABLE Schema.RECOMENDACION ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_REMITENTE)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT RECOMENDACION_USUARIO_FK;

ALTER TABLE Schema.AMISTAD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_2)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT AMISTAD_USUARIO_FK1;

ALTER TABLE Schema.DESCUENTO_ITEM_COMPRABLE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT DESCUENTO_ITEM_COMPRABLE_ITEM_COMPRABLE_FK;

ALTER TABLE Schema.PETICION_AMISTAD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_DESTINATARIO)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT PETICION_AMISTAD_USUARIO_FK1;

ALTER TABLE Schema.MENSAJE_PERFIL ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_REMITENTE)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT MENSAJE_PERFIL_USUARIO_FK;

ALTER TABLE Schema.ALBUM ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT ALBUM_USUARIO_FK;

ALTER TABLE Schema.RECOMENDACION ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_DESTINATARIO)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT RECOMENDACION_USUARIO_FK1;

ALTER TABLE Schema.LOGRO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT LOGRO_JUEGO_FK;

ALTER TABLE Schema.MENSAJE_PERFIL ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_DESTINATARIO)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT MENSAJE_PERFIL_USUARIO_FK1;

ALTER TABLE Schema.BIBLIOTECA ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT BIBLIOTECA_USUARIO_FK;

ALTER TABLE Schema.ITEM_COMPRA ADD CONSTRAINT FOREIGN KEY
	(DESCUENTO_ID)
	REFERENCES Schema.DESCUENTO
	(DESCUENTO_ID)
	CONSTRAINT ITEM_COMPRA_DESCUENTO_FK;

ALTER TABLE Schema.MULTIMEDIA_JUEGO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT MULTIMEDIA_JUEGO_JUEGO_FK;

ALTER TABLE Schema.CONTENIDO_PAQUETE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_JUEGO_ID)
	REFERENCES Schema.JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT CONTENIDO_PAQUETE_JUEGO_FK;

ALTER TABLE Schema.RECOMENDACION ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT RECOMENDACION_ITEM_COMPRABLE_FK;

ALTER TABLE Schema.CUPON_DESCUENTO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT CUPON_DESCUENTO_USUARIO_FK;

ALTER TABLE Schema.JUEGO_PREFERIDO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT JUEGO_PREFERIDO_USUARIO_FK;

ALTER TABLE Schema.BIBLIOTECA ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT BIBLIOTECA_JUEGO_FK;

ALTER TABLE Schema.ITEM_COMPRA ADD CONSTRAINT FOREIGN KEY
	(CUPON_DESCUENTO_ID)
	REFERENCES Schema.CUPON_DESCUENTO
	(CUPON_DESCUENTO_ID)
	CONSTRAINT ITEM_COMPRA_CUPON_DESCUENTO_FK;

ALTER TABLE Schema.COMPRA ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT COMPRA_USUARIO_FK;

ALTER TABLE Schema.CONTENIDO_PAQUETE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_PAQUETE_ID1)
	REFERENCES Schema.PAQUETE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT CONTENIDO_PAQUETE_PAQUETE_FK;

ALTER TABLE Schema.VIDEO_JUEGO ADD CONSTRAINT FOREIGN KEY
	(MULTIMEDIA_JUEGO_ID)
	REFERENCES Schema.MULTIMEDIA_JUEGO
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT VIDEO_JUEGO_MULTIMEDIA_JUEGO_FK;

ALTER TABLE Schema.CUPON_DESCUENTO ADD CONSTRAINT FOREIGN KEY
	(TIPO_CUPON_DESCUENTO_ID)
	REFERENCES Schema.TIPO_CUPON_DESCUENTO
	(TIPO_CUPON_DESCUENTO_ID)
	CONSTRAINT CUPON_DESCUENTO_TIPO_CUPON_DESCUENTO_FK;

ALTER TABLE Schema.JUEGO_PREFERIDO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT JUEGO_PREFERIDO_JUEGO_FK;

ALTER TABLE Schema.ITEM_COMPRA ADD CONSTRAINT FOREIGN KEY
	(COMPRA_ID)
	REFERENCES Schema.COMPRA
	(COMPRA_ID)
	CONSTRAINT ITEM_COMPRA_COMPRA_FK;

ALTER TABLE Schema.LOG_LOGRO_USUARIO ADD CONSTRAINT FOREIGN KEY
	(LOGRO_ID)
	REFERENCES Schema.LOGRO
	(LOGRO_ID)
	CONSTRAINT LOG_LOGRO_USUARIO_LOGRO_FK;

ALTER TABLE Schema.SIMILITUD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_1)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT SIMILITUD_USUARIO_FK;

ALTER TABLE Schema.KEY_ITEM_COMPRABLE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT KEY_ITEM_COMPRABLE_ITEM_COMPRABLE_FK;

ALTER TABLE Schema.IMAGEN_JUEGO ADD CONSTRAINT FOREIGN KEY
	(MULTIMEDIA_JUEGO_ID)
	REFERENCES Schema.MULTIMEDIA_JUEGO
	(MULTIMEDIA_JUEGO_ID)
	CONSTRAINT IMAGEN_JUEGO_MULTIMEDIA_JUEGO_FK;

ALTER TABLE Schema.NOTIFICACION_COMPRA ADD CONSTRAINT FOREIGN KEY
	(COMPRA_ID)
	REFERENCES Schema.COMPRA
	(COMPRA_ID)
	CONSTRAINT NOTIFICACION_COMPRA_COMPRA_FK;

ALTER TABLE Schema.ITEM_COMPRA ADD CONSTRAINT FOREIGN KEY
	(KEY_ID)
	REFERENCES Schema.KEY_ITEM_COMPRABLE
	(KEY_ID)
	CONSTRAINT ITEM_COMPRA_KEY_ITEM_COMPRABLE_FK;

ALTER TABLE Schema.RED_SOCIAL_USUARIO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT RED_SOCIAL_USUARIO_USUARIO_FK;

ALTER TABLE Schema.OBSEQUIO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_DESTINATARIO)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT OBSEQUIO_USUARIO_FK;

ALTER TABLE Schema.LOG_LOGRO_USUARIO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT LOG_LOGRO_USUARIO_USUARIO_FK;

ALTER TABLE Schema.SIMILITUD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_2)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT SIMILITUD_USUARIO_FK1;

ALTER TABLE Schema.JUEGO_DESEADO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT JUEGO_DESEADO_USUARIO_FK;

ALTER TABLE Schema.PAQUETE ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.ITEM_COMPRABLE
	(ITEMCOMPRABLE_ID)
	CONSTRAINT PAQUETE_ITEM_COMPRABLE_FK;

ALTER TABLE Schema.JUEGO ADD CONSTRAINT FOREIGN KEY
	(DESARROLLADOR_ID)
	REFERENCES Schema.DESARROLLADOR
	(DESARROLLADOR_ID)
	CONSTRAINT JUEGO_DESARROLLADOR_FK;

ALTER TABLE Schema.NOTIFICACION_COMPRA ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT NOTIFICACION_COMPRA_USUARIO_FK;

ALTER TABLE Schema.COMENTARIO_JUEGO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT COMENTARIO_JUEGO_JUEGO_FK;

ALTER TABLE Schema.VIDEO_USUARIO ADD CONSTRAINT FOREIGN KEY
	(MULTIMEDIA_USUARIO_ID)
	REFERENCES Schema.MULTIMEDIA_USUARIO
	(MULTIMEDIA_USUARIO_ID)
	CONSTRAINT VIDEO_USUARIO_MULTIMEDIA_USUARIO_FK;

ALTER TABLE Schema.OBSEQUIO ADD CONSTRAINT FOREIGN KEY
	(ITEM_COMPRA_ID)
	REFERENCES Schema.ITEM_COMPRA
	(ITEM_COMPRA_ID)
	CONSTRAINT OBSEQUIO_ITEM_COMPRA_FK;

ALTER TABLE Schema.JUEGO_DESEADO ADD CONSTRAINT FOREIGN KEY
	(ITEMCOMPRABLE_ID)
	REFERENCES Schema.JUEGO
	(ITEMCOMPRABLE_ID)
	CONSTRAINT JUEGO_DESEADO_JUEGO_FK;

ALTER TABLE Schema.JUEGO ADD CONSTRAINT FOREIGN KEY
	(GENERO_ID)
	REFERENCES Schema.GENERO
	(GENERO_ID)
	CONSTRAINT JUEGO_GENERO_FK;

ALTER TABLE Schema.AMISTAD ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID_1)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT AMISTAD_USUARIO_FK;

ALTER TABLE Schema.MULTIMEDIA_USUARIO ADD CONSTRAINT FOREIGN KEY
	(ALBUM_ID)
	REFERENCES Schema.ALBUM
	(ALBUM_ID)
	CONSTRAINT MULTIMEDIA_USUARIO_ALBUM_FK;

ALTER TABLE Schema.COMENTARIO_JUEGO ADD CONSTRAINT FOREIGN KEY
	(USUARIO_ID)
	REFERENCES Schema.USUARIO
	(USUARIO_ID)
	CONSTRAINT COMENTARIO_JUEGO_USUARIO_FK;

ALTER TABLE Schema.DESCUENTO_ITEM_COMPRABLE ADD CONSTRAINT FOREIGN KEY
	(DESCUENTO_ID)
	REFERENCES Schema.DESCUENTO
	(DESCUENTO_ID)
	CONSTRAINT DESCUENTO_ITEM_COMPRABLE_DESCUENTO_FK;

